Update 16-parametrize-helm-chart.yml

diff --git a/.github/workflows/16-parametrize-helm-chart.yml b/.github/workflows/16-parametrize-helm-chart.yml
--- a/.github/workflows/16-parametrize-helm-chart.yml
+++ b/.github/workflows/16-parametrize-helm-chart.yml
@@ -106,10 +106,14 @@ jobs:
           
       - name: Check pgadmin site 
         run: |
-          if ! curl -s http://localhost:8001/login 2>/dev/null; then
+          if ! curl -s http://localhost:8001/login >/dev/null; then
+          exit_code=$?
+          if [ $exit_code -eq 0 ]; then
           echo "pgAdmin does not exist."
           else
-          echo "pgAdmin exists."
+          echo "Unexpected error occurred with curl. Exit code: $exit_code"
           exit 1
           fi
+          fi
+ 
 
