Update 16-parametrize-helm-chart.yml

diff --git a/.github/workflows/16-parametrize-helm-chart.yml b/.github/workflows/16-parametrize-helm-chart.yml
--- a/.github/workflows/16-parametrize-helm-chart.yml
+++ b/.github/workflows/16-parametrize-helm-chart.yml
@@ -106,14 +106,14 @@ jobs:
           
       - name: Check pgadmin site 
         run: |
-          if ! curl -s http://localhost:8002/app >/dev/null; then
-          exit_code=$?
-          if [ $exit_code -eq 0 ]; then
+          curl -s -o /dev/null http://localhost:${{ env.PGADMIN_PORT }}/login
+          curl_exit_code=$?
+
+          if [ $curl_exit_code -eq 52 ]; then
           echo "pgAdmin does not exist."
-          else
-          echo "Unexpected error occurred with curl. Exit code: $exit_code"
+          elif [ $curl_exit_code -eq 0 ]; then
+          echo "pgAdmin exists.Unexpected error occurred with curl. Exit code: $curl_exit_code"
           exit 1
-          fi
           fi
  
 
